// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cinescore-designs/Editorial.tsx": () => import("../components/mockups/cinescore-designs/Editorial.tsx"),
  "./components/mockups/cinescore-designs/Monochrome.tsx": () => import("../components/mockups/cinescore-designs/Monochrome.tsx")
};
